Add testing spec for int.ts file
o1-labs/snarkyjs pull request #164
Opened 2022-05-16 23:17 UTC by MartinMinkov

**Description**
Adds initial test spec for all classes in the `int.ts` file. This includes `Int64`, `UInt64`, and `UInt32`.

There are a number of bugs uncovered while writing unit tests for these classes, some are documented as issues and others are not. I will be looking through our issues list and adding bugs that are not currently present.

The current tests that fail due to bugs are commented out with their error message as a comment. If one wishes to inspect further, uncomment the test and run `npm run test`

2022-05-17 18:48 UTC, bkase requested changes
Wow a lot of test cases, nice!

1. Can you make issues all the failing tests?
2. Is there some way we can test the circuits too? I think right now we're testing the "outside the circuit" version of the logic. We may need to do some crazy ocaml stuff in order to do constraint checking without proof generation (this will be fast, but still catch errors) -- maybe @mitschabaude already knows if this is exposed?

2022-05-17 18:48 UTC, bkase commented on src/lib/int.test.ts
> +    }, 1500);
why is there a long timeout here before we shutdown?

2022-05-17 19:33 UTC, mitschabaude commented
Oh wow, so many failure cases! This is great to have.

> Is there some way we can test the circuits too? I think right now we're testing the "outside the circuit" version of the logic. We may need to do some crazy ocaml stuff in order to do constraint checking without proof generation (this will be fast, but still catch errors) -- maybe @mitschabaude already knows if this is exposed?

I agree that we'd like to have some in-snark testing as well. There's `Circuit.runAndCheck`, I don't know in detail what it does but I think it's designed for exactly that

2022-05-25 16:45 UTC, bkase commented on src/lib/int.test.ts
> +    }, 1500);
SetTimeout 0 as a defer seems okay to me 👍

2022-05-25 16:48 UTC, bkase approved these changes
Awesome!

2022-05-26 09:46 UTC, merged