Add `send` API to zkApp and Party classes
o1-labs/snarkyjs pull request #325
Opened 2022-08-03 19:54 UTC by MartinMinkov

# Description
Implements #281 

Adds the `.send()` method on both the Party and zkApp classes. Additionally added a test script to verify correct behavior.

2022-08-03 20:45 UTC, mitschabaude requested changes

2022-08-03 20:45 UTC, mitschabaude commented on src/lib/party.ts
> +    let receiverParty = Party.createUnsigned(to);
If the `this` party has a non-default token id, then this method could be used to send tokens (e.g., inside the smart contract callback we give to a token contract). This would be cool functionality! However, for this to work, the receiver party must get the same token id. (The current implementation would add Mina on the receiver party but subtract tokens from the `this` party, which would just make the txn fail)

So, I suggest to add the following line here:
```ts
receiverParty.body.tokenId = party.body.tokenId
```

2022-08-03 20:45 UTC, mitschabaude commented on src/lib/party.ts
> +    let receiverParty = Party.createUnsigned(to);
Another thing: We should think about whether we want to make the receiverParty the child of the sender here, by default. Otherwise, the receiver is not linked to the circuit, so I'm scared that a user would add checks on the receiver which would do nothing, and they'd have a security hole that could be exploited

2022-08-03 21:01 UTC, MartinMinkov commented on src/lib/party.ts
> +    let receiverParty = Party.createUnsigned(to);
Ahh, that's a good point I didn't think about. When you say by default, is there a case that the receiverParty wouldn't want to be a child in this case? Seems like we would always want to link the receiver to the circuit to verify its correctness.

2022-08-03 21:19 UTC, mitschabaude commented on src/lib/party.ts
> +    let receiverParty = Party.createUnsigned(to);
Yeah let's do it always for now! I think it might make our lives a little harder when doing the token proofs authorization thing, but we'll figure it out then

2022-08-03 23:04 UTC, MartinMinkov commented on src/lib/party.ts
> +    let receiverParty = Party.createUnsigned(to);
Gotcha, done! :D

2022-08-04 06:08 UTC, mitschabaude approved these changes

2022-08-04 08:46 UTC, ymekuria approved these changes

2022-08-04 09:10 UTC, mitschabaude commented on src/examples/simple-zkapp-payment.ts
> +import {
good point, I think we'll accumulate more & more of those, so I'd add most of them to `/src/examples/zkapps` and reserve `/src/examples` for the most fundamental examples, to not overwhelm a user who explores these

2022-08-04 10:17 UTC, Trivo25 approved these changes

2022-08-04 15:52 UTC, MartinMinkov commented on src/examples/simple-zkapp-payment.ts
> +import {
Sure thing, I'll move it over

2022-08-04 20:13 UTC, merged