Mina-signer JS
o1-labs/snarkyjs pull request #528
Opened 2022-11-04 09:31 UTC by mitschabaude

2022-11-09 14:57 UTC, mitschabaude reviewed
some comments to aid review!

2022-11-09 14:57 UTC, mitschabaude commented on src/lib/events.ts
> +import { prefixToField } from '../provable/binable.js';
Events logic was moved here to make it generic over `Field`

2022-11-09 14:57 UTC, mitschabaude commented on src/lib/circuit_value.ts
> +  function fromJSON(typeObj: any, json: any, isToplevel = false): any {
a major theme of this PR is that `fromJSON` functions were added to all provables

2022-11-09 14:57 UTC, mitschabaude commented on src/lib/encoding.ts
> -function fieldToBase58(x: Field, versionByte: number, versionNumber?: number) {
this code was moved to `provable/binable.ts`

2022-11-09 14:57 UTC, mitschabaude commented on src/lib/hash.ts
> +    let isChecked = !input.every((x) => x.isConstant());
this is a better (more general) way of determining whether to use a "checked" implementation, enables us to clean up code below

2022-11-09 14:57 UTC, mitschabaude commented on src/mina-signer/TSTypes.ts
> +export type UInt32 = number | bigint | string;
this file was just dumped here from Mina/mina-signer and doesn't do anything currently

2022-11-09 14:57 UTC, mitschabaude commented on src/provable/derived-leaves.ts
> +function derivedLeafTypes<Field, Bool>({
one of the many cases where we made an implementation generic over `Field`, so that we can reuse it between snarkyjs & mina-signer

2022-11-09 14:57 UTC, mitschabaude commented on src/provable/from-layout.ts
> +import {
this file used to be called `transaction-helpers.ts`. it is the core of our "derived JS from OCaml" infrastructure. it was extended by adding the `fromJSON` and `emptyValue` functions, and was made generic over `Field`

2022-11-09 14:57 UTC, mitschabaude commented on src/provable/transaction-leaves-bigint.ts
> +import { Field, Bool, UInt32, UInt64, Sign } from './field-bigint.js';
there are now three "transaction-leaves" files. there used to be two
* one for snarkyjs types
* one for JSON types

now we have this third one for mina-signer (bigint-based) types

these files were made much less complex, by auto-generating more code and by moving some common logic to `derived-leaves.ts`

2022-11-09 14:58 UTC, mitschabaude reviewed
some comments to aid review!

2022-11-09 19:55 UTC, mitschabaude commented
Note for reviewers: In the last commit, I copied over the js crypto backend from the Mina repo, without changing anything about it. The intention of doing this here is so that in the next PR, you can better see & review the changes I'm making to it

2022-11-10 15:48 UTC, bkase requested changes
Thanks for the comments to help with review, but I think it's not enough. Sorry for being annoying -- but this is too important to be this difficult to review.

In the future, definitely try to stack PRs for big changes like this instead of having one big one.

But for now, can you rewrite your commit history so a reviewer can read the commits one at a time to understand the PR in smaller chunks? Hopefully, it's not too annoying to set that up.

2022-11-14 15:59 UTC, mitschabaude commented on src/provable/from-layout.ts
> +  function emptyValue(typeData: Layout): any {
this function creates a 'dummy' for an arbitrary type, derived from the layout. this turned out to be necessary, to replace the simpler `emptyValue` function above which just created the value from all-zero field elements. some leaf types have custom `emptyValues`, which aren't all zeroes

2022-11-14 16:04 UTC, mitschabaude commented on src/provable/from-layout.ts
> +            value = emptyValue(optionTypeData.inner);
these changes fix `fromJSON` in the case the JSON has a `null` value in place of a precondition that is specified as a closed interval. the new implementation recreates the proper default interval which is bounded by the min and max values. these values are annotated in OCaml and read off the layout here

2022-11-14 16:04 UTC, mitschabaude commented on src/provable/gen/js-layout.ts
> +                          optionType: 'closedInterval',
changes here are caused by the Mina companion: https://github.com/MinaProtocol/mina/pull/12162

2022-11-14 16:07 UTC, mitschabaude commented on src/js_crypto/bigint256.ts
> +/* global joo_global_object, caml_js_to_bool, caml_jsstring_of_string, caml_string_of_jsstring,
the files in `js_crypto` are just dumped here to modify in the next PR -- please ignore

2022-11-16 01:57 UTC, bkase approved these changes

2022-11-16 19:29 UTC, merged